=== tadamczyk/LabXML_IV/lab5/sklep.dtd
<!ELEMENT Sklep (Zamowienie+)>
<!ELEMENT Zamowienie (Produkt+)>
<!ELEMENT Produkt (Nazwa, Cena, (Ilosc|Sztuk))>
<!ELEMENT Nazwa (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT Ilosc (#PCDATA)>
<!ELEMENT Sztuk (#PCDATA)>
<!ATTLIST Produkt ID CDATA #REQUIRED>
<!ATTLIST Cena Waluta CDATA #REQUIRED>
<!ATTLIST Ilosc Jednostka CDATA #REQUIRED>

=== tadamczyk/LabXML_IV/lab5/sklep.xml
<?xml version="1.0"?>
<!DOCTYPE Sklep SYSTEM "sklep.dtd">
<Sklep>
  <Zamowienie>
    <Produkt ID="1">
      <Nazwa>Kawa rozpuszczalna</Nazwa>
      <Cena Waluta="PL">19.99</Cena>
      <Ilosc Jednostka="KG">2</Ilosc>
    </Produkt>
    <Produkt ID="10">
      <Nazwa>Woda mineralna</Nazwa>
      <Cena Waluta="PL">0.99</Cena>
      <Sztuk>12</Sztuk>
    </Produkt>
  </Zamowienie>
</Sklep>
